class StockTransferPdfGenerator
    def initialize(stock_transfer)
      @stock_transfer = stock_transfer
    end
  
    def generate
      Prawn::Document.new do |pdf|
        pdf.text "Stock Transfer Request From #{User.find_by(id: @stock_transfer.requested_by_id).name}", size: 30, style: :bold
        pdf.move_down 20
  
        # Details
        pdf.text "From Branch : #{Branch.find_by(id: @stock_transfer.branch_id).name}"
        pdf.text "To Branch ID: #{Branch.find_by(id: @stock_transfer.to_branch_id).name}"
        pdf.text "Quantity Transferred: #{@stock_transfer.quantity}"
        pdf.text "Requested By : #{User.find_by(id: @stock_transfer.requested_by_id).name}"
        pdf.text "Approved By: #{User.find_by(id: @stock_transfer.approved_by_id).name}"
        pdf.text "Status: #{@stock_transfer.status}"
        pdf.text "Date: #{@stock_transfer.created_at.strftime('%d/%m/%Y')}"
  
        pdf.move_down 20
  
        # Medicines List
        pdf.text "Medicine Details", size: 18, style: :bold
        pdf.move_down 10
        pdf.table(medicine_data, header: true, row_colors: ['F0F0F0', 'FFFFFF'])
  
        # Footer
        pdf.move_down 30
        pdf.text "Generated by Pharma Site", align: :center
      end
    end
  
    private
  
    def medicine_data
      [['Medicine Name', 'Quantity']] +
      @stock_transfer.medicine_ids.map do |medicine|
        [medicine['name'], medicine['quantity']]
      end
    end
end
  