class V1::GuidelinesController < ApplicationController
  def index
    case current_user.role
    when 'super_admin'
      @screenshots = [
        { image: 'guideimage.png', description: "Super Admin Guide" },
        { image: 'super-admin.png', description: "Super Admin Overview" }
      ]
    when 'cashier'
      @screenshots = [
        { image: 'guideimage.png', description: "Click Next" },
        { image: 'cashier-medicines.png', description: 'You can view the available medicines in the View Medicine section. Also, you can search for the medicines.' },
        { image: 'cashier-bill.png', description: 'You can create a bill for the medicines purchased by the customer and see your weekly sales in your branch.' },
        { image: 'cashier-stock.png', description: 'If medicine is not found, you can request for the medicines from other branches.' }
      ]
    when 'branch_admin'
      @screenshots = [
        { image: 'guideimage.png', description: "Click Next" },
        { image: 'branch-admin-sales.png', description: "You can view your branch's weekly sales generated by the cashiers." },
        { image: 'branch-admin-stock.png', description: "You can view stock requests made by the cashier or make new stock requests for your branch." },
        { image: 'branch-admin-all-medicines.png', description: "You can view all medicines and search for available medicines. Also, you can add and delete medicines." },
        { image: 'branch-admin-new-medicine.png', description: "You can add new medicines by entering their details." },
        { image: 'branch-admin-new-stock.png', description: "Here you can make new stock requests to other branches." }
      ]
    else
      @screenshots = []
    end
  end

  def complete
    flash[:notice] = 'You have completed the guidelines!'
    redirect_to v1_root_path
  end
end
